import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SocketProvider } from "../context/SocketProvider";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Navbar from "./navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Turborepo",
	description: "Generated by create turbo",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}): JSX.Element {
	return (
		<html lang='en'>
			<UserProvider>
				<SocketProvider>
					<body className={inter.className}>
						<Navbar />
						{children}
					</body>
				</SocketProvider>
			</UserProvider>
		</html>
	);
}
